/cam2image:
  ros__parameters:
    width: 300
    height: 200
    socket_ip: 145.126.46.192
    socket_port: 9999
    remote_mode: true
    show_camera: true
    remote_timeout: 7
    history: "keep_last"
    durability: "volatile"
    reliability: "reliable"
    depth: 50
    rotate: false